public class happyindepndenceday {

    public happyindepndenceday(ApexPages.StandardController controller) {

    }
public void forword()
{

integer a=10, b=0, c=10;
//list<String> bits=new list<String>();
String bits;

bits='TFy!QJu ROo TNn(ROo)SLq SLq ULo+UHs UJq TNn*RPn/QPbEWS_JSWQAIJO^NBELPeHBFHT}TnALVlBLOFAkHFOuFETpHCStHAUFAgcEAelclcn^r^r\\tZvYxXyT|S~Pn SPm SOn TNn ULo0ULo#ULo-WHq!WFs XDt!';


while (a != 0) {
//a = bits[b];
b++;
while (a > 64) {
a--;
 
}
}

}

}